/**
 * Serves the service worker with a cache name stamped per deployment.
 *
 * This used to be a static public/sw.js with `const CACHE = "lire-v5"` — a
 * literal that only changed when someone remembered to edit it. Deploys
 * therefore never invalidated anything: the caches from an arbitrarily old
 * build survived, and because the fetch handler falls back to cache whenever
 * the network fails, a flaky connection could serve HTML from a build whose
 * JavaScript chunks no longer exist on the server. That's not a stale page,
 * it's a broken one, and the "new version is ready" banner never fired
 * either, because no new service worker was ever considered installed.
 *
 * Keying the cache on the deployment means every deploy installs a genuinely
 * new worker: `activate` drops every cache that isn't the current one, and
 * the resulting `controllerchange` is what makes the refresh banner in
 * components/ServiceWorker.tsx appear for people already running the app.
 */

/** Read at request time so the value tracks the running deployment rather than whenever this module was first evaluated. */
function deploymentVersion(): string {
  const sha = process.env.VERCEL_GIT_COMMIT_SHA;
  if (sha) return sha.slice(0, 12);
  // Local dev/self-hosted: no deployment id, so fall back to the build stamp
  // Next generates. Worst case this is stable for the process, which is the
  // behaviour we had before, only without the manual version bump.
  return process.env.NEXT_BUILD_ID || "dev";
}

function serviceWorkerSource(version: string): string {
  return `// Generated by src/app/sw.js/route.ts — do not edit a copy in public/.
// Network-first for everything, cache as offline fallback.
const CACHE = "lire-${version}";
const CORE = ["/", "/words", "/review", "/manifest.json", "/icon.svg"];

self.addEventListener("install", (event) => {
  // A failed precache must not block activation, or a single 404 leaves the
  // old worker in charge and the update never lands.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  // Only same-origin GETs are ours to cache; anything else goes straight to
  // the network so third-party requests aren't silently mirrored.
  if (new URL(request.url).origin !== self.location.origin) return;

  event.respondWith(
    fetch(request)
      .then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy)).catch(() => {});
        return res;
      })
      .catch(() => caches.match(request).then((r) => r || caches.match("/")))
  );
});
`;
}

export async function GET(): Promise<Response> {
  return new Response(serviceWorkerSource(deploymentVersion()), {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The worker script itself must never be served from cache, otherwise
      // the browser keeps revalidating against a copy that still names the
      // old cache and the new deployment is never noticed.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
