/**
 * Serves the service worker with a cache name stamped per deployment.
 *
 * This used to be a static public/sw.js with `const CACHE = "lire-v5"` — a
 * literal that only changed when someone remembered to edit it. Deploys
 * therefore never invalidated anything: the caches from an arbitrarily old
 * build survived, and because the fetch handler falls back to cache whenever
 * the network fails, a flaky connection could serve HTML from a build whose
 * JavaScript chunks no longer exist on the server. That's not a stale page,
 * it's a broken one, and the "new version is ready" banner never fired
 * either, because no new service worker was ever considered installed.
 *
 * Keying the cache on the deployment means every deploy installs a genuinely
 * new worker: `activate` drops every cache that isn't the current one, and
 * the resulting `controllerchange` is what makes the refresh banner in
 * components/ServiceWorker.tsx appear for people already running the app.
 */

// A per-process fallback stamp, not per-request: computed once when this
// module first loads, so every request in the same running process (dev
// server or a self-hosted instance with no NEXT_BUILD_ID) shares one cache
// name, but a restart always gets a fresh one — the same "every new instance
// gets a genuinely new worker" guarantee VERCEL_GIT_COMMIT_SHA gives on
// Vercel, just without a fixed commit id to key it on.
const devInstanceStamp = Date.now().toString(36);

/** Read at request time so the value tracks the running deployment rather than whenever this module was first evaluated. */
function deploymentVersion(): string {
  const sha = process.env.VERCEL_GIT_COMMIT_SHA;
  if (sha) return sha.slice(0, 12);
  // Local dev/self-hosted: no deployment id, so fall back to the build stamp
  // Next generates, then to this process's own start time.
  return process.env.NEXT_BUILD_ID || devInstanceStamp;
}

function serviceWorkerSource(version: string): string {
  return `// Generated by src/app/sw.js/route.ts — do not edit a copy in public/.
// Network-first for everything, cache as offline fallback.
const CACHE = "lire-${version}";
const CORE = ["/", "/words", "/review", "/manifest.json", "/icon.svg"];

self.addEventListener("install", (event) => {
  // A failed precache must not block activation, or a single 404 leaves the
  // old worker in charge and the update never lands.
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  // Only same-origin GETs are ours to cache; anything else goes straight to
  // the network so third-party requests aren't silently mirrored.
  if (new URL(request.url).origin !== self.location.origin) return;

  const url = new URL(request.url);
  const isNavigation = request.mode === "navigate";

  event.respondWith(
    fetch(request)
      .then((res) => {
        const cacheControl = res.headers.get("cache-control") || "";
        const cacheableDestination = isNavigation || ["style", "script", "image", "font", "manifest"].includes(request.destination);
        const mayCache =
          res.ok &&
          res.status === 200 &&
          cacheableDestination &&
          !url.pathname.startsWith("/api/") &&
          url.pathname !== "/sw.js" &&
          !request.headers.has("authorization") &&
          !/(?:no-store|private)/i.test(cacheControl);

        if (mayCache) {
          const copy = res.clone();
          // Cache the copy in the background via waitUntil rather than
          // chaining it before returning res: a streamed navigation response
          // (this app's App Router pages all stream) isn't "complete" until
          // its body has fully arrived, and respondWith won't hand anything
          // back to the page until this promise settles — so awaiting the
          // cache write first held the entire page hostage to how long its
          // own streaming took to finish, which for some routes never
          // resolved in practice. The page gets res immediately either way;
          // caching it is a side effect, not a gate.
          event.waitUntil(
            caches
              .open(CACHE)
              .then((cache) => cache.put(request, copy))
              .catch(() => {})
          );
        }
        return res;
      })
      .catch(async () => {
        const cached = await caches.match(request);
        if (cached) return cached;
        // Only a document navigation may fall back to the offline shell.
        // APIs and missing JS/CSS/assets must fail as their own response type,
        // never receive homepage HTML that callers then try to parse/execute.
        if (isNavigation) return (await caches.match("/")) || Response.error();
        return Response.error();
      })
  );
});
`;
}

export async function GET(): Promise<Response> {
  return new Response(serviceWorkerSource(deploymentVersion()), {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The worker script itself must never be served from cache, otherwise
      // the browser keeps revalidating against a copy that still names the
      // old cache and the new deployment is never noticed.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
